### ISSUE TITLE
Convert reaper-account-id to String 

### ISSUE THREAD

**Issue by sshaw** [xendk/reaper#10]
Hi, thanks for this project.

Since the account ID is an integer (at least for me) I just did:

```el
(setq reaper-account-id MYID)
```

But that resulted in a `Wrong type argument: stringp`. 

Would be good to convert (`format`) this to a string before using.

**Comment by xendk** [comment]
Well, the `defcustom` does say it's a string. If you're `setq`ing custom variables, you should be careful with types, the `defcustom` *is* the type checking.

**Comment by sshaw** [comment]
> If you're setqing custom variables, you should be careful with types

I'm just an innocent user. It's the developers job to make the API solid and easy to use

> Well, the defcustom does say it's a string. 

What am I supposed to look at source code to figure out the correct type?
Or maybe you're purposing I weed through the customization UI in the hopes of finding your group and this variable name. 

This does not make an API, easy to use...

> the defcustom is the type checking

No, defcustom is an optional UI

**Comment by xendk** [comment]
> I'm just an innocent user. It's the developers job to make the API solid and easy to use

Custom is the official interface to the variable. It's mentioned in the readme. It's easy to use.

> What am I supposed to look at source code to figure out the correct type?
> Or maybe you're purposing I weed through the customization UI in the hopes of finding your group and this variable name.

`C-h v` or `M-x describe-variable` and you'll get a link to both the custom UI and the source line. Or you could take the hint from the default value being an empty string.

> This does not make an API, easy to use...

It's not an API, it's a variable used by a library. It's not common for emacs packages to be explicit of the type of the variables in their documentation string, so one might have to inspect some code to figure it out. But custom is explicit about types, so this makes it easier that if it was just a regular `defvar`. 

> No, defcustom is an optional UI

Which does type checking. If you want to mess with variables of libraries that uses custom, fine, you're free to do so, but you should look at the variable definition to ensure you're passing the right type.

**Comment by sshaw** [comment]
From your docs:

> Create a personal access token at https://id.getharvest.com/developers and customize reaper-api-key to the given value. 

Instead of "customize" (which is what I did, e.g., `setq`) I would suggest:

> Create a personal access token at https://id.getharvest.com/developers and set  reaper-api-key to the given value via Emacs' Customize interface
---

> This does not make an API, easy to use...

> > It's not an API, it's a variable used by a library.

I would really suggest looking up the definition of API 📖

**Comment by sshaw** [comment]
But do note software is in large part about usability, so adding `format("%s", reaper-account-id)` somewhere is what's going to make it more usable. Anything else is just internet ranting and bikeshedding.

**Comment by xendk** [comment]
> Instead of "customize" (which is what I did, e.g., setq) I would suggest:

In the context of Emacs, the word "customize" has a very specific meaning. Just like "fork" has in Unix. But I've updated the readme.

> I would really suggest looking up the definition of API 

Wikipedia:
> An application programming interface (API) is an interface or communication protocol between different parts of a computer program intended to simplify the implementation and maintenance of software. 

You'll find that most definitions of API define it as an interface between two pieces of software. What we're talking about is a variable that reaper defines and reaper uses.

> But do note software is in large part about usability, so adding format("%s", reaper-account-id) somewhere is what's going to make it more usable. 

So it makes it more usable that I add `(format "%s" reaper-account-id)` in two places, rather than you add the two `"` needed to fix your problem, which only exist because you refuse to use the standard Emacs interface designed exactly for allowing users to provide input to packages without the pitfalls of `setq`?

> Anything else is just internet ranting and bikeshedding.

Yet you persist. I've pointed out that customize is the officially supported method, it's the standard method of Emacs, even use-package interfaces with it. You're free to not use it, but then you take on the responsibility of having to figure out the types for yourself, and risk getting an error if you mess up.

**Comment by sshaw** [comment]
Ha. I would suggest you also look up "interface". But, since you kindly referred to Wikipedia, maybe just look at the 3rd paragraph:

> An API specification can take many forms, but often includes specifications for routines, data structures, object classes, variables, or remote calls. POSIX, Windows API and ASPI are examples of different forms of APIs. Documentation for the API usually is provided to facilitate usage and implementation.
 
`$?` in Bash and `errno` in C come to mind. Oh, and `reaper-account-id`, or course 😉 

> Anything else is just internet ranting and bikeshedding.

>> Yet you persist. 

😂

✌

**Comment by xendk** [comment]
Interface? As in User Interface? That's quite a way from API.

But yes, customize is the user interface. 

Elisp being what it is doesn't distinguish between public and private interface/structure. The closest thing being the convention that double dash signifies private functions/variables, but that's not enforced. Rather, everything is left open, with the understanding that if you open the can, you can break things. So it doesn't make much sense to talk about an API.

I certainly haven't defined an API for reaper. Don't expect it would find any use. If someone wants a certain new behavior, they're free to "break it open" so to speak, and implement it how they see fit, with the understanding that they might run into conflicts if I release a new version. And I hope that anyone that creates something useful creates a pull request so others might benefit.

> $? in Bash and errno in C come to mind. Oh, and reaper-account-id, or course

A major difference is that the first two is for output, while reaper-account-id is for input.
