### ISSUE TITLE
Admins can see all people's entries

### ISSUE THREAD

**Issue by aaronjensen** [xendk/reaper#12]
I'm a harvest admin and when I take a look at the reaper buffer, I see everyone's entries for that day. It should only show my own.

**Comment by xendk** [comment]
Indeed it should.

I'll add a lookup of the current user and using the id in the request when I get some time.

**Comment by xendk** [comment]
@aaronjensen should be fixed now.

**Comment by aaronjensen** [comment]
Thank you for the quick fix, much appreciated.
