### ISSUE TITLE
Error running timer ‘reaper--update-timer’: (wrong-type-argument timerp nil)

### ISSUE THREAD

**Issue by akoppela** [xendk/reaper#2]
Please guide me if I'm wrong. The error in title is visible when the buffer is killed. What is the correct way to use `reaper`. Is the correct way to never kill the buffer?

**Comment by akoppela** [comment]
For some reason the timer is not removed with `cancel-timer` function.

**Comment by xendk** [comment]
Well, the error is an error, `reaper--update-timer` fogets to check if the timer is set before cancelling it. I'll fix that.

You're right, it's not really suppposed to be killed. It caches data in buffer variables, (noteworthy it caches the project/task list, which is notoriously slow to get here).

Just press `q`, it'll bury the buffer and remove the window. You'll not see it in the buffer list as it's hidden, but `reaper` will bring it back. Actually, in the next version `RET` wont just start a timer, but also bury the buffer, for quick switching (`SPC` will just start the timer).

But I still need to figure out how to cancel the timer when the buffer is killed.
