### ISSUE TITLE
The layout is slightly off.

### ISSUE THREAD

**Issue by akoppela** [xendk/reaper#3]
Hi. The layout is slightly off, isn't it? Do you think It's something you'd like to fix? Or is that something with my config?

![IMG_0266](https://user-images.githubusercontent.com/56569/64532699-9b678380-d344-11e9-8910-50757be4ba98.jpeg)

**Comment by xendk** [comment]
I think that's `linenum-mode`or equivalent getting in the way, try disabling it.

I would guess you'd get the same sort of problem in any `tabulated-list-mode`.

**Comment by akoppela** [comment]
https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/tabulated-list.el#L263

As per source code of tabulated list line number padding should be supported. In fact where I enable debugging for `tabulated-list-init-header` function I can see that the header padded correctly. It seems like either the window is not selected before `reaper-mode` is called or maybe a list of entries is empty and thus it affects the line width number. But I think it's the former.

**Comment by xendk** [comment]
Oh, good digging.

I can see the problem if I enable `display-line-numbers-mode` in the reaper buffer. Refreshing with either `r` or `g` doesn't fix it. I'll look into where the header is init'ed.

**Comment by akoppela** [comment]
The patch commit did not fix the issue. I can confirm that it's related to the fact that time entries are empty. It seems that the fix can be to run `tabulated-list-init-header` after the time entries are received from Harvest. Or at least it can be a direction.

**Comment by xendk** [comment]
OK, can you try #8 and see if that fixes it?

**Comment by akoppela** [comment]
I can confirm that #8 fixes the issue.

**Comment by xendk** [comment]
Merged then.
