### ISSUE TITLE
Add a way to view total amount of logged hours.

### ISSUE THREAD

**Issue by akoppela** [xendk/reaper#9]
At the moment to see a total amount of logged hours I still go to the website. It would be nice to show total amount of logged hours either in table or by sending `message` by pressing key-binding. What do you think?

**Comment by xendk** [comment]
As long as we're not allowing the table to be sorted, we can add a totals line at the end. Just need to make sure that functions that takes the entry at point know how to ignore it. It's probably also the easiest as it can be done when constructing the list, and the current timer would automatically ensure it's also kept up to date.

**Comment by xendk** [comment]
Sorry it took so long. Reapers' been way down on my priority list.

**Comment by akoppela** [comment]
Awesome
